# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.4.1"
    steps:
      - checkout
      - run:
         name: Install cocoapods
         command: sudo gem install cocoapods -v 1.8.4
      - run:
         name: Install pods
         command: pod install
      - run:
          name: Run Tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 11

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
